
DROP DATABASE IF EXISTS bb_db;
CREATE DATABASE bb_db;
USE bb_db;


CREATE TABLE RECIEPE (
  ID      			INT            PRIMARY KEY  AUTO_INCREMENT,
  NAME				VARCHAR(100)   NOT NULL     UNIQUE,
  STYLE				VARCHAR(12)	   NOT NULL,
  IBU			    INT(3.2)  	   NOT NULL,
  ABV				INT(2.1)	   NOT NULL,
  SRM				INT(2.1),
  GRAIN_BILL		VARCHAR(25)	   NOT NULL,
  HOP				VARCHAR(12)	   NOT NULL,
  YEAST				VARCHAR(12.2)  NOT NULL,
  OTHER_ING			VARCHAR(20)
 );
 
CREATE TABLE GRAIN (
  ID				INT				PRIMARY KEY	AUTO_INCREMENT,
  VENDOR_CODE		INT(25)			NOT NULL,
  NAME				VARCHAR(25)		NOT NULL,
  TYPE				VARCHAR(8)		NOT NULL,
  LOVIBOND			VARCHAR(2.2)	NOT NULL
  );
  
CREATE TABLE HOP (
  ID				INT				PRIMARY KEY AUTO_INCREMENT,
  NAME				VARCHAR(10)		NOT NULL,
  PURPOSE			VARCHAR(12)		NOT NULL,
  ALPHA_ACID		VARCHAR(2.2)	NOT NULL
  );

CREATE TABLE YEAST (
ID					INT				PRIMARY KEY AUTO_INCREMENT,
NAME				VARCHAR(10)		NOT NULL,
STYLE				VARCHAR(12)		NOT NULL,
ATTENUATION			VARCHAR(4)		NOT NULL,
FLOCUATION			VARCHAR(4)		NOT NULL,
CELL_DENSITY		VARCHAR(8.4)	NOT NULL,
ALCOHOL_TOL			VARCHAR(4)		NOT NULL	
);

CREATE TABLE ADDITIVE (
ID					INT				PRIMARY KEY AUTO_INCREMENT,
NAME				VARCHAR(25)		NOT NULL,
TYPE				VARCHAR(4)		NOT NULL,
PURPOSE				VARCHAR(100)	NOT NULL	
);

CREATE TABLE MASH (
ID					INT 			PRIMARY KEY AUTO_INCREMENT,
DURATION			varchar(2.2)    NOT NULL,
TEMPERATURE			INT(3.2)		NOT NULL,
STRIKE_TEMP			INT(3.2)		NOT NULL,
STRIKE_VOLUME		INT(2.2)		NOT NULL,
SPARGE_TEMP			INT(3.2)		NOT NULL,
SPARGE_VOLUME		INT(2.2)		NOT NULL,
MASHOUT_VOLUME		INT(2.2)		NOT NULL,
MASH_THICKNESS		INT(1.2)		NOT NULL				
);

CREATE TABLE BOIL (
ID					INT 			PRIMARY KEY AUTO_INCREMENT,
WORT_VOLUME			INT(2.2)		NOT NULL,
DURATION 			VARCHAR(2.2)	NOT NULL,
ADDITIONS			VARCHAR(25)		NOT NULL
);

CREATE TABLE FERMENTATION (
ID					INT				PRIMARY KEY AUTO_INCREMENT,
YEAST				VARCHAR(12)		NOT NULL,
PITCH_RATE			VARCHAR(8.4)	NOT NULL,
ATTENUATION			VARCHAR(4)		NOT NULL,
TEMPERATURE			INT(2.1)		NOT NULL,
ORIGINAL_GRAVITY	INT(2.2)		NOT NULL,
FINAL_GRAVITY		INT(2.2)		NOT NULL
);

INSERT INTO RECIPE VALUES
(1,'RHINEGIEST TRUTH CLONE','IPA','72.3','7.2','6.54',(364,324,382),(1,2,3,4),(1),(1,2,3,4,5)
);

INSERT INTO GRAIN VALUES
();

INSERT INTO HOP VALUES 
();

INSERT INTO YEAST VALUES
();

INSERT INTO ADDITIVE VALUES
();

INSERT INTO MASH VALUES
();

INSERT INTO BOIL VALUES
();

INSERT INTO FERMENTATION VALUES
();




-- create a user and grant privileges to that user
-- GRANT SELECT, INSERT, DELETE, UPDATE
-- ON bank_db

-- IDENTIFIED BY 'sesame';