DROP DATABASE IF EXISTS bb_db;
CREATE DATABASE bb_db;
USE bb_db;


CREATE TABLE RECIPE (
  ID      			INT            PRIMARY KEY  AUTO_INCREMENT,
  NAME				VARCHAR(100)   NOT NULL     UNIQUE,
  STYLE				VARCHAR(12)	   NOT NULL,
  IBU			    INT(3.2)  	   NOT NULL,
  ABV				INT(2.1)	   NOT NULL,
  SRM				INT(2.1),
  GRAIN_BILL		VARCHAR(25)	   NOT NULL,
  HOP				VARCHAR(12)	   NOT NULL,
  YEAST				VARCHAR(12.2)  NOT NULL,
  OTHER_ING			VARCHAR(20)
 );
 
CREATE TABLE GRAIN (
  ID				INT				PRIMARY KEY	AUTO_INCREMENT,
  VENDOR_CODE		INT(25)			NOT NULL,
  NAME				VARCHAR(25)		NOT NULL,
  LOVIBOND			VARCHAR(2.2)	NOT NULL
  );
  
 CREATE TABLE GRAIN_BILL (
 ID					INT 			PRIMARY KEY AUTO_INCREMENT,
 BASE 				VARCHAR(40)		NOT NULL,
 ADJUNCT1			VARCHAR(40),
 ADJUNCT2			VARCHAR(40),
 ADJUNCT3			VARCHAR(40)		
 ); 
  
CREATE TABLE HOP (
  ID				INT				PRIMARY KEY AUTO_INCREMENT,
  NAME				VARCHAR(10)		NOT NULL,
  ALPHA_ACID		VARCHAR(2.2)	NOT NULL,
  FLAVOR			VARCHAR(225)
  );
  
 CREATE TABLE HOP_PROFILE (
 ID					int				PRIMARY KEY AUTO_INCREMENT,
 FIRSTWORT			VARCHAR(20),
 HOP1				VARCHAR(20),
 HOP2				VARCHAR(20),
 HOP3				VARCHAR(20),
 HOP4				VARCHAR(20),
 DRY1				VARCHAR(20),
 DRY2				VARCHAR(20)
 ); 

CREATE TABLE YEAST (
ID					INT				PRIMARY KEY AUTO_INCREMENT,
NAME				VARCHAR(25)		NOT NULL,
STYLE				VARCHAR(12)		NOT NULL,
ATTENUATION			VARCHAR(4)		NOT NULL,
FLOCUATION			VARCHAR(4)		NOT NULL,
CELL_DENSITY		VARCHAR(25)		NOT NULL,
ALCOHOL_TOL			VARCHAR(4)		NOT NULL	
);

CREATE TABLE ADDITIVE (
ID					INT				PRIMARY KEY AUTO_INCREMENT,
NAME				VARCHAR(25)		NOT NULL,
TYPE				VARCHAR(20)		NOT NULL,
PURPOSE				VARCHAR(100)	NOT NULL	
);

CREATE TABLE MASH (
ID					INT 			PRIMARY KEY AUTO_INCREMENT,
DURATION			varchar(2.2)    NOT NULL,
TEMPERATURE			INT(3.2)		NOT NULL,
STRIKE_TEMP			INT(3.2)		NOT NULL,
STRIKE_VOLUME		INT(2.2)		NOT NULL,
SPARGE_TEMP			INT(3.2)		NOT NULL,
SPARGE_VOLUME		INT(2.2)		NOT NULL,
MASHOUT_VOLUME		INT(2.2)		NOT NULL,
MASH_THICKNESS		INT(1.2)		NOT NULL				
);

CREATE TABLE BOIL (
ID					INT 			PRIMARY KEY AUTO_INCREMENT,
WORT_VOLUME			INT(2.2)		NOT NULL,
DURATION 			VARCHAR(2.2)	NOT NULL,
ADDITIONS			VARCHAR(25)		NOT NULL
);

CREATE TABLE FERMENTATION (
ID					INT				PRIMARY KEY AUTO_INCREMENT,
YEAST				VARCHAR(12)		NOT NULL,
PITCH_RATE			VARCHAR(30)		NOT NULL,
ATTENUATION			VARCHAR(4)		NOT NULL,
TEMPERATURE			INT(2.1)		NOT NULL,
ORIGINAL_GRAVITY	INT(2.2)		NOT NULL,
FINAL_GRAVITY		INT(2.2)		NOT NULL
);

INSERT INTO RECIPE VALUES
(1,'RHINEGIEST TRUTH CLONE','IPA','72.3','7.2','6.54','bomb','thingy','thinga','thing'
);

INSERT INTO GRAIN VALUES
(1,'363','Page 2 Row','30');

INSERT INTO GRAIN_BILL VALUES
(1,'2 ROW PALE MALT','AMERICAN VIENNA','CARA RED','0');

INSERT INTO HOP VALUES 
(1,'Citra','11','Intense citrus flavor');

INSERT INTO HOP_PROFILE VALUES
(1,'FIRSTWORT','HOP1','HOP2','HOP3','HOP4','DRY1','DRY2');

INSERT INTO YEAST VALUES
(1,'Wyeast 1056','American Ale','High','High','1million,gram','High');

INSERT INTO ADDITIVE VALUES
(1,'Yeast Nutrient','Boil Additive','Used to promote growth of cell walls in yeast');

INSERT INTO MASH VALUES
(1,'60','1','2','3','4','5','6','7');

INSERT INTO BOIL VALUES
(1,'7','60','8');

INSERT INTO FERMENTATION VALUES
(1,'Wyeast 1056','1 Billion','High','68','10.58','10.10');




-- create a user and grant privileges to that user
-- GRANT SELECT, INSERT, DELETE, UPDATE
-- ON bank_db

-- IDENTIFIED BY 'sesame';